// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT8wx7LXSE2XCukqA4rzvdY-v0-dLM1gc',
    appId: '1:173450847574:web:3c198b9042241ea701a2f7',
    messagingSenderId: '173450847574',
    projectId: 'project-uas-a6a01',
    authDomain: 'project-uas-a6a01.firebaseapp.com',
    storageBucket: 'project-uas-a6a01.appspot.com',
    measurementId: 'G-XGM0ES00RQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5KbEc6CDG5K4AxsLD3EyjpVM5B-0zTPI',
    appId: '1:173450847574:android:1d6d579d6ec89bba01a2f7',
    messagingSenderId: '173450847574',
    projectId: 'project-uas-a6a01',
    storageBucket: 'project-uas-a6a01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAILrT8h9hH0TlITczeyflh2_RhpCVrQrE',
    appId: '1:173450847574:ios:fbfac3c61de21cf301a2f7',
    messagingSenderId: '173450847574',
    projectId: 'project-uas-a6a01',
    storageBucket: 'project-uas-a6a01.appspot.com',
    iosBundleId: 'com.example.flutterlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAILrT8h9hH0TlITczeyflh2_RhpCVrQrE',
    appId: '1:173450847574:ios:fbfac3c61de21cf301a2f7',
    messagingSenderId: '173450847574',
    projectId: 'project-uas-a6a01',
    storageBucket: 'project-uas-a6a01.appspot.com',
    iosBundleId: 'com.example.flutterlist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAT8wx7LXSE2XCukqA4rzvdY-v0-dLM1gc',
    appId: '1:173450847574:web:d945d3003a084b7f01a2f7',
    messagingSenderId: '173450847574',
    projectId: 'project-uas-a6a01',
    authDomain: 'project-uas-a6a01.firebaseapp.com',
    storageBucket: 'project-uas-a6a01.appspot.com',
    measurementId: 'G-J2HSE02DSM',
  );
}
